# apiVersion: v1 
# kind: Secret
# metadata: 
#   name: backend-secret
# data: 
#   database_url: "cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBsb2NhbGhvc3Q6NTQzMgo="

apiVersion: v1 
kind: Secret
metadata: 
  name: backend-secret
data: 
  .env: "REFUQUJBU0VfVVJMPXBvc3RncmVzOi8vcG9zdGdyZXM6cGFzc3dvcmRAbG9jYWxob3N0OjU0MzIKQVdTX1NFQ1JFVD0xMjNqbGtqMjMxaTMKUE9SVD0zMDAwClBVQkxJQ19LRVk9MTIza2xrZHNmYWFzCkpXVF9TRUNSRVQ9MTJhc2FkMjEzYWQ="